Repository OCFL/spec, pull requests merged in 2018-07, with the labels that each got.

#32 Move conformance declaration into right section
  index.html
Labels: Section 3

#31 Version directory naming
  index.html
Labels: Section 3

#34 Fixed: Add section on inventory sidecar files
  index.html
Labels: Section 4

#36 New: Added section on digest algorithm
  index.html
Labels: Section 4

#43 Fixed: Add NAMASTE reference in object declaration
  index.html
Labels: Section 1, ready-for-review
