Repository OCFL/spec, pull requests merged in 2018-09, with the labels that each got.

#99 Logs Directory definition.
  index.html
Labels: Section 2

#105 Directories definition
  index.html
Labels: Section 2

#109 Definition for existing file path
  index.html
Labels: Section 2

#110 Definition for Logical File Path
  index.html
Labels: Section 2

#111 Logical state definition
  index.html
Labels: Section 2

#124 Update terms and define object root and storage root
  index.html
Labels: Section 2

#139 OCFL Object definition
  draft/spec/index.html
Labels: Section 2

#157 Create _config.yml
  _config.yml
Labels: Editorial, Ready for Review

#160 Link to implementation notes from intro, fix link
  draft/spec/index.html
Labels: Editorial
